# 音楽コレクション用のディレクトリ
OldiesDir = '/home/radish/oldies'
NewiesDir = '/home/radish/newies'

# バックアップ用ディレクトリ
BackupDir = '/tmp/backup'

# コピー用の一意なディレクトリ名
timestamp = Time.new.to_s.tr(" :", "_")

# rakeタスク
task :default => [:backup_oldies, :backup_newies]

task :backup_oldies do
  backup_dir = File.join(BackDir, timestamp, OldiesDir)
  mkdir_p File.dirname(backup_dir)
  cp_r OldiesDir, backup_dir
end

task :backup_newies do
  backup_dir = File.join(BackDir, timestamp, NewiesDir)
  mkdir_p File.dirname(backup_dir)
  cp_r NewiesDir, backup_dir
end